language: python

services:
- postgresql

env:
- DATABASE_URL='postgres://postgres:@localhost:5432/sermonbuddy_test' SECRET_KEY='tT\xd7\xb06\xf7\x9b\xff\x0fZL\xca\xca\x11\xefM\xacr\xfb\xdf\xca\x9b'

python:
- '2.7'

addons:
  postgresql: "9.3"

install:
- pip install -r REQUIREMENTS-dev.txt
- nodeenv -p --node=0.10.31
- npm -g install yuglify



before_script:
  - psql -c 'create database gis;' -U postgres
  - psql -c 'create extension postgis;' gis -U postgres
  - cd django_project
  - python manage.py collectstatic --noinput --settings=core.settings.dev_travis

script:
  - python manage.py test --settings=core.settings.test_travis
